export const patients = [
  {
    id: 1,
    username: "test1",
    first_name: "Phil",
    last_name: "Thomas",
    email: "test1@test.com",
    has_insurance: true,
    insurance_name: "Harvard Pilgrim",
    type: "patient"
  },
  {
    id: 2,
    username: "test2",
    first_name: "Mark",
    last_name: "Holdings",
    email: "test2@test.com",
    has_insurance: true,
    insurance_name: "Blue Cross",
    type: "patient"
  },
  {
    id: 3,
    username: "test3",
    first_name: "Kyle",
    last_name: "Chad",
    email: "test3@test.com",
    has_insurance: false,
    insurance_name: undefined,
    type: "patient"
  },
  {
    id: 4,
    username: "test4",
    first_name: "John",
    last_name: "Johnson",
    email: "test4@test.com",
    has_insurance: false,
    insurance_name: undefined,
    type: "doctor"
  },
  {
    id: 5,
    username: "test5",
    first_name: "Arthur",
    last_name: "McDingus",
    email: "test5@test.com",
    has_insurance: true,
    insurance_name: "Blue Shield",
    type: "patient"
  }
];

export const procedures = [
  {
    id: 1,
    user_id: 1,
    username: "anonymous",
    procedure_name: "unicorn horn removal",
    hosptial_name: "Mercy Hospital",
    city: "Pine Bluff",
    state: "AR",
    zip: 71601,
    street: "2300 S Olive St",
    docotor: "Dr. Smithington",
    procedure_cost: 2000,
    insurance_payment: 1500,
    insurance_adjustment: 200,
    out_of_pocket: 300
  },
  {
    id: 2,
    user_id: 2,
    username: "test2",
    procedure_name: "tonsillectomy",
    hosptial_name: "Generic Hospital",
    city: "Pine Bluff",
    state: "AR",
    zip: 71601,
    street: "1601 S Cherry St",
    docotor: "Dr. Red",
    procedure_cost: 5000,
    insurance_payment: 2000,
    insurance_adjustment: 0,
    out_of_pocket: 3000
  },
  {
    id: 3,
    user_id: 3,
    username: "test3",
    procedure_name: "nostril-Alignment",
    hosptial_name: "Jefferson Regional Medical Center",
    city: "Pine Bluff",
    state: "AR",
    zip: 71603,
    street: "1600 W 40th Ave",
    docotor: "Dr. Red",
    procedure_cost: 3000,
    insurance_payment: 1700,
    insurance_adjustment: 200,
    out_of_pocket: 1100
  },
  {
    id: 4,
    user_id: 4,
    username: "test4",
    procedure_name: "upper rendo-petriculum atropocathy",
    hosptial_name: "Memphis Zoo",
    city: "Memphis",
    state: "TN",
    zip: 38112,
    street: "2000 Prentiss Pl",
    docotor: "Dr. Octopus",
    procedure_cost: 1000,
    insurance_payment: 800,
    insurance_adjustment: 200,
    out_of_pocket: 0
  },
  {
    id: 5,
    user_id: 1,
    username: "anonymous",
    procedure_name: "big boo-boo",
    hosptial_name: "Meeman-Shelby Forest State Park",
    city: "Millington",
    state: "TN",
    zip: 38053,
    street: "910 Riddick Rd",
    docotor: "Karen",
    procedure_cost: 200,
    insurance_payment: 0,
    insurance_adjustment: 0,
    out_of_pocket: 200
  },
  {
    id: 6,
    user_id: 1,
    username: "anonymous",
    procedure_name: "big boo-boo",
    hosptial_name: "Meeman-Shelby Forest State Park",
    city: "Millington",
    state: "TN",
    zip: 38053,
    street: "910 Riddick Rd",
    docotor: "Karen",
    procedure_cost: 200,
    insurance_payment: 0,
    insurance_adjustment: 0,
    out_of_pocket: 200
  },
  {
    id: 7,
    user_id: 1,
    username: "anonymous",
    procedure_name: "big boo-boo",
    hosptial_name: "Meeman-Shelby Forest State Park",
    city: "Millington",
    state: "TN",
    zip: 38053,
    street: "910 Riddick Rd",
    docotor: "Karen",
    procedure_cost: 200,
    insurance_payment: 0,
    insurance_adjustment: 0,
    out_of_pocket: 200
  },
  {
    id: 8,
    user_id: 1,
    username: "anonymous",
    procedure_name: "big boo-boo",
    hosptial_name: "Meeman-Shelby Forest State Park",
    city: "Millington",
    state: "TN",
    zip: 38053,
    street: "910 Riddick Rd",
    docotor: "Karen",
    procedure_cost: 200,
    insurance_payment: 0,
    insurance_adjustment: 0,
    out_of_pocket: 200
  },
  {
    id: 9,
    user_id: 1,
    username: "anonymous",
    procedure_name: "big boo-boo",
    hosptial_name: "Meeman-Shelby Forest State Park",
    city: "Millington",
    state: "TN",
    zip: 38053,
    street: "910 Riddick Rd",
    docotor: "Karen",
    procedure_cost: 200,
    insurance_payment: 0,
    insurance_adjustment: 0,
    out_of_pocket: 200
  }
];
